/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Entidades;

import Sound.SoundPlayer;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author joaoluis
 */
public class dialogueBox extends javax.swing.JPanel {
    ArrayList<String> dialogues;
    int dialogueIndex;
    String speaker;
    String soundPath;
    
    /**
     * Creates new form dialogueBox
     */
    public dialogueBox(String speaker, String first_dialogue) {
        this.speaker = speaker;
        this.dialogues = new ArrayList<String>();
        initComponents();
        this.dialogues.add(first_dialogue);
        dialogueField.setText(first_dialogue);
        characterName.setText(speaker);
        dialogues.get(dialogueIndex).chars().forEach((c) -> {
            SoundPlayer.playSound(getSoundPath());
        });
       }
    public void setAuthorIcon(String path){
        authorIcon.setIcon(new ImageIcon(path));
    }
    
    public void addDialogue(String sentence){
        dialogues.add(sentence);
    }
    public ArrayList<String> getDialogues(){
        return dialogues;
    }
    public void setDialogues(ArrayList<String> dialogues){
        this.dialogues = dialogues;
    }
    public int getDialogueIndex(){
        return dialogueIndex;
    }
    public void passDialogue(){
        this.dialogueIndex = (dialogueIndex + 1);
        if(dialogueIndex >= dialogues.size()){
        java.awt.Container parent = this.getParent(); 

            if (parent != null) { 
                parent.remove(this); 
                parent.revalidate(); 
                parent.repaint(); 
                return;
            }
        }
            
        dialogues.get(dialogueIndex).chars().forEach((c) -> {
            SoundPlayer.playSound(getSoundPath());
        });
        dialogueField.setText(dialogues.get(dialogueIndex));
    }
    public String getCurrentDialogue(){
        return dialogues.get(dialogueIndex);
    }

    public String getSoundPath() {
        return soundPath;
    }

    public void setSoundPath(String soundPath) {
        this.soundPath = soundPath;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorIcon = new javax.swing.JLabel();
        characterName = new javax.swing.JLabel();
        dialogueField = new javax.swing.JTextField();
        nextDialogButton = new javax.swing.JButton();

        authorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/circle.png"))); // NOI18N

        characterName.setText("Character name");

        dialogueField.setEditable(false);
        dialogueField.setText("Dialogue");
        dialogueField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dialogueField.setFocusable(false);
        dialogueField.setVerifyInputWhenFocusTarget(false);
        dialogueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogueFieldActionPerformed(evt);
            }
        });

        nextDialogButton.setText("Próximo");
        nextDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passDialogue(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextDialogButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(characterName)
                            .addComponent(dialogueField, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorIcon)
                    .addComponent(dialogueField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextDialogButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dialogueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogueFieldActionPerformed

    private void passDialogue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passDialogue
        passDialogue();
    }//GEN-LAST:event_passDialogue


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorIcon;
    private javax.swing.JLabel characterName;
    private javax.swing.JTextField dialogueField;
    private javax.swing.JButton nextDialogButton;
    // End of variables declaration//GEN-END:variables
}
