/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Entidades;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL; 
/**
 *
 * @author joaoluis
 */
public class Sprite extends javax.swing.JPanel {
    
    private String state = "normal";
    private String name = "jombson"; 
    private int maxFrames;
    private int currentFrame = 0; 
    private Timer animationTimer;
    /**
     * Creates new form Sprite
     */
    public Sprite() {
        initComponents();
        this.maxFrames = 4; 
        this.currentFrame = 1; 
        setupAnimation(); 
    }


    public Sprite(String name, String state, int maxFrames) {
        initComponents();
        this.name = name;
        this.state = state;
        this.maxFrames = maxFrames;
        this.currentFrame = 1; 
        setupAnimation();
    }
    
    private void setupAnimation() {
        int frameDelay = 100; 

        animationTimer = new Timer(frameDelay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentFrame++;
                if (currentFrame > maxFrames) {
                    currentFrame = 1; 
                }
                updateSpriteImage();
            }
        });
        animationTimer.start(); 
    }
    
    private void updateSpriteImage() {
        String frameNumber = String.format("%04d", currentFrame);
        String imagePath = "/trabalho/resources/sprites/" + name + "/" + name + "-" + state + "-" + frameNumber + ".png";
        
        URL imageUrl = getClass().getResource(imagePath);
        if (imageUrl != null) {
            spriteLabel.setIcon(new ImageIcon(imageUrl));
            revalidate();
            repaint();
        } else {
            System.err.println("Erro: Imagem não encontrada: " + imagePath);
            animationTimer.stop(); 
        }
    }



    public String getState() {
        return state;
    }

    public void setState(String state) {
        if (!this.state.equals(state)) {
            this.state = state;
            this.currentFrame = 1; 
            updateSpriteImage();
        }
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        updateSpriteImage();
    }

    public int getMaxFrames() {
        return maxFrames;
    }

    public void setMaxFrames(int maxFrames) {
        this.maxFrames = maxFrames;
        if (this.currentFrame > maxFrames) {
            this.currentFrame = 1;
        }
        updateSpriteImage();
    }

    public int getCurrentFrame() {
        return currentFrame;
    }

    public void setCurrentFrame(int currentFrame) {
        this.currentFrame = currentFrame;
        updateSpriteImage();
    }

    public JLabel getSpriteLabel() {
        return spriteLabel;
    }

    public void setSpriteLabel(JLabel spriteLabel) {
        this.spriteLabel = spriteLabel;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spriteLabel = new javax.swing.JLabel();

        setOpaque(false);

        spriteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/sprites/jombson/Jombson-0001.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel spriteLabel;
    // End of variables declaration//GEN-END:variables
}
