/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Entidades;

import javax.swing.ImageIcon;

/**
 *
 * @author joaoluis
 */
public class Sprite extends javax.swing.JPanel {
    
    String state = 'normal';
    String name = 'jobmson';
    int maxFrames;
    int currentFrame;
    /**
     * Creates new form Sprite
     */
    public Sprite() {
        initComponents();
        while(true){
            for(int i = 0; i < maxFrames; i++){
                spriteLabel.setIcon(new ImageIcon(name + "-" + state + "-" + currentFrame));
            }
  
        }
    }

    public Sprite(String state , String name , int currentFrame, int maxFrames) {
        this.state = state;
        this.name = name;
        this.maxFrames = maxFrames;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spriteLabel = new javax.swing.JLabel();

        setOpaque(false);

        spriteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/sprites/jombson/Jombson-0001.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spriteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel spriteLabel;
    // End of variables declaration//GEN-END:variables
}
