/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import Entidades.Unemployed;
import Entidades.GameLoop;
import Sound.SoundPlayer;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

import Sound.SoundPlayer;
import Entidades.*;
/**
 *
 * @author joaoluis
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Player player;
    
    public Game() {
        initComponents();
        System.out.println(System.getProperty("user.dir"));
        SoundPlayer.playSound("./src/trabalho/resources/audio/menu.wav");
        String name = null;
        do {
            name = JOptionPane.showInputDialog(null, "Qual é seu nome?");
        }
        while(name == null);
  
        this.player = new Player(0, name, new Unemployed("farol", name, 1.0));
        moneyLabel.setText(player.getMoney()+" R$");
        professionLabel.setText(player.getProfession().toString());
        employeeLabel.setText(player.getEmployees().size() + " empregados");
        
        Story gameStory = new Story(this, dialoguePane, player);
               
        GameLoop gameLoop = new GameLoop(player, this, gameStory);
        gameLoop.startGameLoop();
        
        // start tutorial
        
       
        gameStory.meetTheAntagonist();
      

   
        
    }

    public JLabel getEventLabel() {
        return eventLabel;
    }

    public void setEventLabel(JLabel eventLabel) {
        this.eventLabel = eventLabel;
    }

    public JLabel getMoneyLabel() {
        return moneyLabel;
    }

    public void setMoneyLabel(JLabel moneyLabel) {
        this.moneyLabel = moneyLabel;
    }

    public JLabel getProfessionLabel() {
        return professionLabel;
    }

    public void setProfessionLabel(JLabel professionLabel) {
        this.professionLabel = professionLabel;
    }

    public JLabel getEmployeeLabel() {
        return employeeLabel;
    }

    public void setEmployeeLabel(JLabel employeeLabel) {
        this.employeeLabel = employeeLabel;
    }
    
    
    
  

    private void buttonAnimation(JButton targetButton, String filename){
        String pressedPath = ("/trabalho/resources/buttons/" + filename + "_pressed.png");
        String buttonPath = ("/trabalho/resources/buttons/" + filename + ".png");
        targetButton.setIcon(new ImageIcon(getClass().getResource(pressedPath)));
        Timer timer = new Timer(100, e -> {
            targetButton.setIcon(new ImageIcon(getClass().getResource(buttonPath)));
        });
        timer.setRepeats(false);
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        workButton = new javax.swing.JButton();
        professionLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dialoguePane = new javax.swing.JLayeredPane();
        eventLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Workonomia: Simulador de trabalho");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));

        employeeLabel.setFont(new java.awt.Font("Lato Semibold", 0, 15)); // NOI18N
        employeeLabel.setForeground(new java.awt.Color(102, 102, 102));
        employeeLabel.setText("0 empregados");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/Money.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(10, 10));

        jLabel3.setMaximumSize(new java.awt.Dimension(10, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/employees.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(10, 10));

        moneyLabel.setFont(new java.awt.Font("Lato Heavy", 1, 15)); // NOI18N
        moneyLabel.setForeground(new java.awt.Color(0, 204, 204));
        moneyLabel.setText("00.00 R$");

        workButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/work.png"))); // NOI18N
        workButton.setBorder(null);
        workButton.setContentAreaFilled(false);
        workButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workButtonActionPerformed(evt);
            }
        });

        professionLabel.setFont(new java.awt.Font("Lato Semibold", 0, 15)); // NOI18N
        professionLabel.setForeground(new java.awt.Color(102, 102, 102));
        professionLabel.setText("Desempregado");
        professionLabel.setToolTipText("");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/profession.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(workButton))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(professionLabel)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLabel)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(workButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialoguePaneLayout = new javax.swing.GroupLayout(dialoguePane);
        dialoguePane.setLayout(dialoguePaneLayout);
        dialoguePaneLayout.setHorizontalGroup(
            dialoguePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        dialoguePaneLayout.setVerticalGroup(
            dialoguePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(dialoguePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(eventLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dialoguePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void workButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workButtonActionPerformed
        buttonAnimation(workButton, "work");
        player.addMoney(1);
        moneyLabel.setText(player.getMoney() + "R$");
        eventLabel.setText(player.getProfession().doJobActivity());
        SoundPlayer.playSound("src/trabalho/resources/audio/money.wav");
        
    }//GEN-LAST:event_workButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane dialoguePane;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JButton workButton;
    // End of variables declaration//GEN-END:variables
}
