/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import Entidades.Unemployed;
import Sound.SoundPlayer;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

import Sound.SoundPlayer;
import Entidades.*;
/**
 *
 * @author joaoluis
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Player player;
    
    public Game() {
        initComponents();
        System.out.println(System.getProperty("user.dir"));
        SoundPlayer.playSound("./src/trabalho/resources/audio/menu.wav");
        String name = null;
        do {
            name = JOptionPane.showInputDialog(null, "Qual é seu nome?");
        }
        while(name == null);
  
        this.player = new Player(0, name, new Unemployed("farol"));
        moneyLabel.setText(player.getMoney()+" R$");
        employeeLabel.setText(player.getEmployees().size() + " empregados");
        
        // start tutorial,
       // start tutorial
        dialogueBox tutorial = new dialogueBox("Jombson", "(Jombson te encara de cima a baixo, um suspiro quase inaudível escapa.) ... O que foi?");
        tutorial.addDialogue("Qual é o seu nome, garoto? Anda, não tenho o dia todo.");
        tutorial.addDialogue(player.getName() + "?... É, combina.");
        tutorial.addDialogue("Você. É, você mesmo. Não olhe pros lados. Essa cara de desespero... Típico de quem não tem onde cair morto.");
        tutorial.addDialogue("Meu nome é Jombson. Guarde bem, talvez um dia precise implorar por algo. Sou o cérebro por trás... bem, de tudo que importa por aqui. E hoje, num raro momento de tédio, decidi notar sua insignificante existência.");
        tutorial.addDialogue("E não, antes que crie esperanças, você *não* trabalha pra mim. Isso é um luxo. E você, claramente, não tem nenhum.");
        tutorial.addDialogue("Mas sabe o que me diverte? Ver gente como você rastejar. É... inspirador, à sua maneira.");
        tutorial.addDialogue("Vê aquele farol caindo aos pedaços ali? É o seu novo 'palácio'. Perfeito pra quem não pode escolher.");
        tutorial.addDialogue("Sua 'missão', se é que podemos chamar assim: vá pra lá e venda água. Sim, água. Para os idiotas presos no trânsito.");
        tutorial.addDialogue("Não me olhe com essa cara. Ordens são para serem cumpridas, não entendidas.");
        tutorial.addDialogue("Cada garrafa vendida? Um mísero real. É quase um insulto, eu sei. Mas é mais do que você vale agora.");
        tutorial.addDialogue("Tem um botão aí... 'Trabalhar', ou algo do tipo. Veja se consegue ao menos *isso*. Me prove que você entende o conceito de 'clicar' e 'obedecer'. Não me decepcione... mais.");
        tutorial.addDialogue("Faça isso. Quem sabe, *quem sabe*, se você não me irritar demais ou tropeçar nos próprios pés, eu te jogue um osso maior.");
        tutorial.addDialogue("Mas por agora, menos conversa e mais servilismo. Venda. Toda grande fortuna começa com alguém engolindo o orgulho por trocados. E você tem *muito* orgulho pra engolir.");
        tutorial.setSize(tutorial.getPreferredSize()); 
        tutorial.setSoundPath("./src/trabalho/resources/audio/jombson.wav");
        dialoguePane.add(tutorial, JLayeredPane.PALETTE_LAYER);
       int x = (dialoguePane.getWidth() - tutorial.getWidth()) / 2;
       int y = (dialoguePane.getHeight() - tutorial.getHeight()) / 2;
       tutorial.setLocation(x, y);

        tutorial.setVisible(true); 
        tutorial.playVoice();
        this.revalidate();
        this.repaint();    
   
        
    }

    private void buttonAnimation(JButton targetButton, String filename){
        String pressedPath = ("/trabalho/resources/buttons/" + filename + "_pressed.png");
        String buttonPath = ("/trabalho/resources/buttons/" + filename + ".png");
        targetButton.setIcon(new ImageIcon(getClass().getResource(pressedPath)));
        Timer timer = new Timer(100, e -> {
            targetButton.setIcon(new ImageIcon(getClass().getResource(buttonPath)));
        });
        timer.setRepeats(false);
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        workButton = new javax.swing.JButton();
        dialoguePane = new javax.swing.JLayeredPane();
        eventLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("playerMoney");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));

        employeeLabel.setFont(new java.awt.Font("Lato Semibold", 0, 15)); // NOI18N
        employeeLabel.setForeground(new java.awt.Color(102, 102, 102));
        employeeLabel.setText("0 empregados");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/Money.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(10, 10));

        jLabel3.setMaximumSize(new java.awt.Dimension(10, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/employees.png"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(10, 10));

        moneyLabel.setFont(new java.awt.Font("Lato Heavy", 1, 15)); // NOI18N
        moneyLabel.setForeground(new java.awt.Color(0, 204, 204));
        moneyLabel.setText("00.00 R$");

        workButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/resources/buttons/work.png"))); // NOI18N
        workButton.setBorder(null);
        workButton.setContentAreaFilled(false);
        workButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(workButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(workButton)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialoguePaneLayout = new javax.swing.GroupLayout(dialoguePane);
        dialoguePane.setLayout(dialoguePaneLayout);
        dialoguePaneLayout.setHorizontalGroup(
            dialoguePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        dialoguePaneLayout.setVerticalGroup(
            dialoguePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(dialoguePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(eventLabel)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dialoguePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void workButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workButtonActionPerformed
        buttonAnimation(workButton, "work");
        player.addMoney(1);
        moneyLabel.setText(player.getMoney() + "R$");
        eventLabel.setText(player.getProfession().doJobActivity());
        SoundPlayer.playSound("src/trabalho/resources/audio/money.wav");
        
    }//GEN-LAST:event_workButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane dialoguePane;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JButton workButton;
    // End of variables declaration//GEN-END:variables
}
